apiVersion: v1
kind: Pod
metadata:
  name: send-email
  namespace: default
spec:
  containers:
  - name: send-email
    image: brentgroves/send-email-docker:1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  

