apiVersion: v1
kind: Pod
metadata:
  name: send-email-hostnetwork
  namespace: default
spec:
  hostNetwork: true
  dnsPolicy: Default
  containers:
  - name: send-email
    image: brentgroves/send-email-hostnetwork:1
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always  

